import ExpandingBox from "../components/ExpandingBox";

export const Ch7Content = () => {
  return (
    <div className="course-content">
      <h2 className="section-heading">Role of the Parser</h2>
      <p className="p-text">
        In the compilation pipeline, the <strong>Syntax Analyzer (Parser)</strong> is the second phase. It takes the token stream generated by the Lexical Analyzer (Lexer) and checks whether the tokens form valid expressions according to the grammatical rules of the programming language.
      </p>
      
      <div className="flex justify-center my-6">
        <div className="bg-[#FAE8D7] text-[#1B0D00] p-4 rounded border-2 border-[#1B0D00] font-mono text-sm max-w-lg w-full text-center">
          Tokens Stream &rarr; [ Parser ] &rarr; Parse Tree / Syntax Tree
          <div className="text-[11px] mt-1 text-[#7a5c3a] border-t border-[#1B0D00]/20 pt-1">
            Interacts with Symbol Table &amp; Reports Errors
          </div>
        </div>
      </div>

      <h2 className="section-heading">Context-Free Grammars (CFGs)</h2>
      <p className="p-text">
        A Context-Free Grammar is a formal mathematical system used to define the syntax of a language. It is defined as a 4-tuple:
      </p>
      <div className="bg-black/20 p-4 rounded-lg border border-[#c7a669]/30 my-4 font-mono text-sm">
        <strong>G = (V, T, P, S)</strong>
        <ul className="list-disc list-inside mt-2 space-y-1">
          <li><strong>V</strong>: A finite set of non-terminal variables (syntactic categories).</li>
          <li><strong>T</strong>: A finite set of terminal symbols (actual tokens/words).</li>
          <li><strong>P</strong>: A set of production rules mapping variables to strings of variables and terminals (e.g., A &rarr; &alpha;).</li>
          <li><strong>S</strong>: The start symbol (S &isin; V).</li>
        </ul>
      </div>

      <h2 className="section-heading">Derivations and Parse Trees</h2>
      <p className="p-text">
        A <strong>Derivation</strong> is the sequence of production steps used to generate a target string from the start symbol. There are two primary types of derivations:
      </p>
      <ul className="list-disc list-inside space-y-2 p-text mb-4">
        <li><strong>Leftmost Derivation (LMD)</strong>: At each step, the leftmost non-terminal is replaced first.</li>
        <li><strong>Rightmost Derivation (RMD)</strong>: At each step, the rightmost non-terminal is replaced first.</li>
      </ul>

      <ExpandingBox title="Ambiguity in Grammars — Solved Example">
        <p className="p-text">
          A grammar is <strong>ambiguous</strong> if there exists a string that has more than one leftmost derivation, rightmost derivation, or parse tree.
        </p>
        <p className="p-text font-bold mt-2">
          Given Grammar (Expression Grammar):
        </p>
        <pre className="bg-[#FAE8D7] text-[#1B0D00] p-3 rounded font-mono text-sm my-2">
          E &rarr; E + E | E * id | id
        </pre>
        <p className="p-text">
          We want to trace the string: <code className="bg-[#FAE8D7]/30 px-1 rounded">id + id * id</code>.
        </p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
          <div className="border border-[#c7a669]/40 p-4 rounded">
            <h4 className="font-bold text-[#c7a669] mb-2">Parse Tree 1: (id + id) * id</h4>
            <p className="text-sm italic mb-2">Evaluates addition first (leaves * at the top level).</p>
            <pre className="font-mono text-xs text-[#e2d1c1] bg-black/40 p-2 rounded">
{`      E
    / | \\
   E  *  id
 / | \\
E  +  E
|     |
id    id`}
            </pre>
            <p className="text-xs mt-2 text-[#a07840]">
              <strong>LMD:</strong> E &rArr; E * id &rArr; E + E * id &rArr; id + E * id &rArr; id + id * id
            </p>
          </div>

          <div className="border border-[#c7a669]/40 p-4 rounded">
            <h4 className="font-bold text-[#c7a669] mb-2">Parse Tree 2: id + (id * id)</h4>
            <p className="text-sm italic mb-2">Evaluates multiplication first (leaves + at the top level).</p>
            <pre className="font-mono text-xs text-[#e2d1c1] bg-black/40 p-2 rounded">
{`      E
    / | \\
   id +  E
       / | \\
      E  *  id
      |
      id`}
            </pre>
            <p className="text-xs mt-2 text-[#a07840]">
              <strong>LMD:</strong> E &rArr; E + E &rArr; id + E &rArr; id + E * id &rArr; id + id * id
            </p>
          </div>
        </div>

        <p className="p-text mt-4 text-red-300">
          <strong>Conclusion:</strong> Since the string has two distinct parse trees representing different operator precedences, the grammar is <strong>ambiguous</strong>.
        </p>
      </ExpandingBox>

      <h2 className="section-heading">Elimination of Left Recursion</h2>
      <p className="p-text">
        Top-down parsers (like LL(1)) enter infinite loops when a grammar has <strong>Left Recursion</strong> (where a production looks like A &rarr; A&alpha;). We must eliminate this syntax pattern.
      </p>
      
      <div className="border-l-4 border-[#c7a669] pl-4 my-4">
        <h4 className="font-bold text-lg text-[#c7a669]">Direct Left Recursion Rule:</h4>
        <p className="p-text my-1">Given a left-recursive production:</p>
        <pre className="bg-[#FAE8D7] text-[#1B0D00] p-2 rounded font-mono text-sm inline-block">
          A &rarr; A&alpha; | &beta;
        </pre>
        <p className="p-text my-1">Rewrite it as:</p>
        <pre className="bg-[#FAE8D7] text-[#1B0D00] p-2 rounded font-mono text-sm inline-block">
          A &rarr; &beta;A&apos;
          A&apos; &rarr; &alpha;A&apos; | &epsilon;
        </pre>
      </div>

      <h2 className="section-heading">Elimination of Left Factoring</h2>
      <p className="p-text">
        <strong>Left Factoring</strong> is a grammar transformation useful for resolving choices when two alternative productions start with the same prefix. It allows top-down parsers to defer the decision until they see what comes after the shared prefix.
      </p>
      <div className="border-l-4 border-[#c7a669] pl-4 my-4">
        <h4 className="font-bold text-lg text-[#c7a669]">Left Factoring Rule:</h4>
        <p className="p-text my-1">Given productions with a common prefix:</p>
        <pre className="bg-[#FAE8D7] text-[#1B0D00] p-2 rounded font-mono text-sm inline-block">
          A &rarr; &alpha;&beta;_1 | &alpha;&beta;_2
        </pre>
        <p className="p-text my-1">Factor out the prefix:</p>
        <pre className="bg-[#FAE8D7] text-[#1B0D00] p-2 rounded font-mono text-sm inline-block">
          A &rarr; &alpha;A&apos;
          A&apos; &rarr; &beta;_1 | &beta;_2
        </pre>
      </div>
    </div>
  );
};
