import React from "react";
import ExpandingBox from "../components/ExpandingBox";

export const Ch5Content = () => {
  return (
    <div className="course-content">
      <p className="p-text">
        In this chapter, we explore how compilers compile themselves, and how to construct compilers that generate machine code for architectures different from the ones they are running on.
      </p>

      <section>
        <h3 className="section-heading">The Bootstrapping Paradox</h3>
        <p className="p-text mt-2">
          Bootstrapping is the process of writing a compiler for a language in that same language. It presents a classic chicken-and-egg paradox: <em>how do you compile a compiler written in language X when you don&apos;t yet have a compiler that runs X?</em>
        </p>

        <ExpandingBox title="The Bootstrapping Paradox Explained" defaultOpen={true}>
          <p>
            To compile the compiler source (written in X), you need a binary compiler for X. But you are currently writing that very binary.
          </p>
          <div className="note-box my-3">
            <strong>Solution:</strong>
            <ol className="list-decimal pl-5 mt-1 space-y-1">
              <li>Write a compiler for a small subset of the language <code>X0</code> in assembly/machine code.</li>
              <li>Use that subset compiler to compile a compiler for the full language <code>X</code> written in <code>X0</code>.</li>
              <li>You now have a running compiler for <code>X</code>! From here, you can rewrite your compiler in full <code>X</code> and compile it with itself. This state is called <strong>self-hosting</strong>.</li>
            </ol>
          </div>
        </ExpandingBox>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">T-Diagrams (Tombstone Diagrams)</h3>
        <p className="p-text mt-2">
          T-Diagrams provide a formal visual notation for describing compilers. A compiler is defined by three languages:
        </p>
        <ul className="section-list my-2">
          <li><strong>Source Language (S):</strong> The input language (left).</li>
          <li><strong>Target Language (T):</strong> The output language (right).</li>
          <li><strong>Implementation Language (I):</strong> The language the compiler is written in (bottom).</li>
        </ul>

        <ExpandingBox title="T-Diagram Notation & Combination Rules" defaultOpen={false}>
          <pre className="code-block">{`          S ----> T
             \\   /
              \\ /
               I

Combination Rule (Compiler cascade):
If you have a compiler translating S -> T written in M:
   Compiler 1: [S -> T] written in M
And a compiler/processor translating M -> U written in H:
   Compiler 2: [M -> U] written in H

You can feed Compiler 1's source code (written in M) into Compiler 2, resulting in:
   [S -> T] written in U!`}</pre>
        </ExpandingBox>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">Cross Compilers</h3>
        <p className="p-text mt-2">
          A <strong>Cross Compiler</strong> is a compiler that runs on one host machine <code>H</code>, but generates machine instructions for a different target machine <code>T</code> (where <code>H ≠ T</code>).
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-4">
          <div className="card">
            <h4 className="font-bold text-lg mb-1 text-[#5b3a29]">Why are they necessary?</h4>
            <p className="text-sm">
              Essential for embedded systems and IoT devices (like microcontrollers or mobile phones) that are too slow or have too little memory to run a full compiler suite themselves.
            </p>
          </div>
          <div className="card">
            <h4 className="font-bold text-lg mb-1 text-[#5b3a29]">Example</h4>
            <p className="text-sm">
              Compiling C code on your x86-64 Intel laptop to generate ARM binary instructions to deploy on a Raspberry Pi or an iOS/Android smartphone.
            </p>
          </div>
        </div>

        <ExpandingBox title="Canadian Cross Compilation" defaultOpen={false}>
          <p>
            A complex but standard build configuration in systems engineering involving three machines:
          </p>
          <ul className="section-list my-2 space-y-1">
            <li><strong>Build Machine (A):</strong> Where the compiler is actually built.</li>
            <li><strong>Host Machine (B):</strong> Where the compiler executable will run.</li>
            <li><strong>Target Machine (C):</strong> Where the binary outputs generated by the compiler will run.</li>
          </ul>
          <p className="mt-2 text-sm italic">
            This is commonly used in compiling GCC toolchains for new target architectures when a native compiler does not exist on the target architecture.
          </p>
        </ExpandingBox>
      </section>
    </div>
  );
};
