import React from "react";
import ExpandingBox from "../components/ExpandingBox";

export const Ch3Content = () => {
  return (
    <div className="course-content">
      <p className="p-text">
        Writing a compiler from scratch is a massive undertaking. To address this complexity, the CS community developed specialized tools called <span className="font-semibold">Compiler Writing Tools</span> (or Compiler-Compilers) that automate the most mathematically complex parsing and scanning logic.
      </p>

      <section>
        <h3 className="section-heading">Key Automated Tools</h3>
        <div className="overflow-x-auto my-4">
          <table className="w-full border-collapse border border-[#c7a669] text-left text-sm md:text-base">
            <thead>
              <tr className="bg-[#7a523c] text-[#fff7ed]">
                <th className="border border-[#c7a669] p-3 font-semibold">Phase Targeted</th>
                <th className="border border-[#c7a669] p-3 font-semibold">Tool</th>
                <th className="border border-[#c7a669] p-3 font-semibold">Description</th>
              </tr>
            </thead>
            <tbody className="bg-[#f3e7c2]/20 dark:bg-black/20 text-[#3A2A14] dark:text-[#f3e7c2]">
              <tr>
                <td className="border border-[#c7a669] p-3 font-bold">Lexical Analysis</td>
                <td className="border border-[#c7a669] p-3">Lex / Flex</td>
                <td className="border border-[#c7a669] p-3">Generates O(n) DFA-based lexical scanners from regular expression rules.</td>
              </tr>
              <tr>
                <td className="border border-[#c7a669] p-3 font-bold">Syntax Analysis</td>
                <td className="border border-[#c7a669] p-3">Yacc / Bison</td>
                <td className="border border-[#c7a669] p-3">Generates LALR(1) parsers from Context-Free Grammars (CFG) in Backus-Naur Form (BNF).</td>
              </tr>
              <tr>
                <td className="border border-[#c7a669] p-3 font-bold">Intermediate & Backend</td>
                <td className="border border-[#c7a669] p-3">LLVM</td>
                <td className="border border-[#c7a669] p-3">A modern library infrastructure for code optimization and hardware target translation.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">1. LEX / FLEX</h3>
        <p className="p-text mt-2">
          Lex reads a specification file (typically ending in <code>.l</code>) containing regular expressions, and produces a C source file containing a fast finite-automaton scanner function <code>yylex()</code>.
        </p>

        <ExpandingBox title="Structure of a LEX File (.l)" defaultOpen={false}>
          <p>A Lex specification file is split into three sections separated by <code>%%</code> delimiters:</p>
          <pre className="code-block">{`%{
/* Section 1: C Declarations */
#include <stdio.h>
%}

/* Section 2: Definitions (regex patterns) */
digit   [0-9]
letter  [a-zA-Z]

%%
/* Section 3: Rules (Pattern & matching action) */
{digit}+    { printf("INTEGER: %s\\n", yytext); }
{letter}+   { printf("WORD: %s\\n", yytext); }
.           { /* ignore everything else */ }
%%

/* Section 4: User Subroutines */
int yywrap() { return 1; }`}</pre>
        </ExpandingBox>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">2. YACC / BISON</h3>
        <p className="p-text mt-2">
          Yacc (Yet Another Compiler-Compiler) takes a context-free grammar specification (usually ending in <code>.y</code>) and generates an LALR(1) bottom-up parser function <code>yyparse()</code>.
        </p>

        <ExpandingBox title="Structure of a YACC File (.y)" defaultOpen={false}>
          <p>Like Lex, Yacc files use <code>%%</code> split markers for definitions, grammar rules, and helper C code:</p>
          <pre className="code-block">{`%{
#include <stdio.h>
int yylex();
void yyerror(const char *s);
%}

%token NUMBER ID
%left '+' '-'
%left '*' '/'

%%
/* Grammar Rules */
expr : expr '+' expr   { $$ = $1 + $3; }
     | expr '*' expr   { $$ = $1 * $3; }
     | NUMBER          { $$ = $1; }
     ;
%%

void yyerror(const char *s) {
    fprintf(stderr, "Parsing error: %s\\n", s);
}`}</pre>
        </ExpandingBox>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">LEX + YACC Integration</h3>
        <p className="p-text mt-2">
          In practice, the lexical scanner generated by Lex acts as a helper to the parser generated by Yacc. The parser calls <code>yylex()</code> each time it needs a new token.
        </p>

        <ExpandingBox title="Integrated Execution Loop Diagram" defaultOpen={false}>
          <div className="bg-[#f3e7c2] text-center border border-[#c7a669] p-4 rounded-xl text-[#3A2A14] space-y-2">
            <div className="font-bold text-lg">Source File</div>
            <div className="text-xl">↓</div>
            <div className="bg-[#7a523c] text-white p-2 rounded">LEX Scanner (yylex)</div>
            <div className="text-sm">Matches characters to match token patterns, returning Token Code and storing attribute in yylval</div>
            <div className="text-xl">↓ Token Code</div>
            <div className="bg-[#5b3a29] text-white p-2 rounded">YACC Parser (yyparse)</div>
            <div className="text-sm">Validates context-free grammar constraints and executes semantic block code actions</div>
            <div className="text-xl">↓</div>
            <div className="font-bold text-lg">Abstract Syntax Tree (AST)</div>
          </div>
        </ExpandingBox>
      </section>

      <hr className="my-6 border-[#c7a669] opacity-40" />

      <section>
        <h3 className="section-heading">Modern Alternatives</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-4">
          <div className="card">
            <h4 className="font-bold text-lg mb-1 text-[#5b3a29]">ANTLR4</h4>
            <p className="text-sm">
              Generates LL(*) parsers supporting multiple target languages (Java, C++, Python, JavaScript) from unified <code>.g4</code> grammar files.
            </p>
          </div>
          <div className="card">
            <h4 className="font-bold text-lg mb-1 text-[#5b3a29]">LLVM</h4>
            <p className="text-sm">
              Translates frontend-produced LLVM IR (Static Single Assignment form) into optimized target machine code for x86, ARM, RISC-V, etc.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};
